version: "3"

services:
  web:
    build: . 
    volumes: 
      - .:/app
    ports: 
      - "4567:4567"
    depends_on:
      - db
    command: bundle exec ruby myapp.rb -o 0.0.0.0

  nginx:
    image: nginx:latest
    volumes: 
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf.template
      - ./public:/var/www/html
    ports:
      - "8080:8080"
    depends_on:
      - web
    environment:
        #- DOCKER_IP=192.168.99.100
        #- DOCKER_IP=127.0.0.1
        - DOCKER_IP=127.0.0.1
    command: /bin/bash -c "envsubst '$$DOCKER_IP' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"

  db:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "latestgram"
      MYSQL_USER: "root"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
